services:
  webapi:
    image: imbrahiam/webapi:latest
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    volumes:
      - C:/Users/Brahiam/.aspnet/https:/https:ro
      - datakeys:/var/aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SedisDocker$
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dockersedis.pfx
      - ConnectionStrings__DefaultConnection=Server=database;Database=Sedis;User Id=sa;Password=SedisSQLServer$;TrustServerCertificate=True;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=sedis
      - RabbitMQ__Password=7uFO^f`{*2n1
    container_name: sedis-api
    ports:
      - '8080:80' # HTTP
      - '8081:443' # HTTPS
    depends_on:
      - database
      - rabbitmq
    networks:
      - sedis-network
    restart: always

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SedisSQLServer$
    ports:
      - '1439:1433'
    networks:
      - sedis-network
    volumes:
      - mssql-data:/var/opt/mssql
    container_name: sedis-database
    restart: always

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=sedis
      - RABBITMQ_DEFAULT_PASS=7uFO^f`{*2n1
    networks:
      - sedis-network
    container_name: sedis-rabbitmq
    restart: always

networks:
  sedis-network:
    driver: bridge

volumes:
  mssql-data:
  datakeys: